/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * PortainerEE API
 * Portainer API is an HTTP API served by Portainer. It is used by the Portainer UI and everything you can do with the UI can be done using the HTTP API.
Examples are available at https://documentation.portainer.io/api/api-examples/
You can find out more about Portainer at [http://portainer.io](http://portainer.io) and get some support on [Slack](http://portainer.io/slack/).

# Authentication

Most of the API environments(endpoints) require to be authenticated as well as some level of authorization to be used.
Portainer API uses JSON Web Token to manage authentication and thus requires you to provide a token in the **Authorization** header of each request
with the **Bearer** authentication mechanism.

Example:

```
Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOjEsImV4cCI6MTQ5OTM3NjE1NH0.NJ6vE8FY1WG6jsRQzfMqeatJ4vh2TWAeeYfDhP71YEE
```

# Security

Each API environment(endpoint) has an associated access policy, it is documented in the description of each environment(endpoint).

Different access policies are available:

- Public access
- Authenticated access
- Restricted access
- Administrator access

### Public access

No authentication is required to access the environments(endpoints) with this access policy.

### Authenticated access

Authentication is required to access the environments(endpoints) with this access policy.

### Restricted access

Authentication is required to access the environments(endpoints) with this access policy.
Extra-checks might be added to ensure access to the resource is granted. Returned data might also be filtered.

### Administrator access

Authentication as well as an administrator role are required to access the environments(endpoints) with this access policy.

# Execute Docker requests

Portainer **DO NOT** expose specific environments(endpoints) to manage your Docker resources (create a container, remove a volume, etc...).

Instead, it acts as a reverse-proxy to the Docker HTTP API. This means that you can execute Docker requests **via** the Portainer HTTP API.

To do so, you can use the `/endpoints/{id}/docker` Portainer API environment(endpoint) (which is not documented below due to Swagger limitations). This environment(endpoint) has a restricted access policy so you still need to be authenticated to be able to query this environment(endpoint). Any query on this environment(endpoint) will be proxied to the Docker API of the associated environment(endpoint) (requests and responses objects are the same as documented in the Docker API).

# Private Registry

Using private registry, you will need to pass a based64 encoded JSON string ‘{"registryId":\<registryID value\>}’ inside the Request Header. The parameter name is "X-Registry-Auth".
\<registryID value\> - The registry ID where the repository was created.

Example:

```
eyJyZWdpc3RyeUlkIjoxfQ==
```

**NOTE**: You can find more information on how to query the Docker API in the [Docker official documentation](https://docs.docker.com/engine/api/v1.30/) as well as in [this Portainer example](https://documentation.portainer.io/api/api-examples/).

 * OpenAPI spec version: 2.19.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse, AxiosError } from 'axios';
import { useMutation } from 'react-query';
import type { UseMutationOptions, MutationFunction } from 'react-query';

import type {
  GitopsFileResponse,
  GitopsRepositoryFilePreviewPayload,
  GitopsRepositoryFileSearchPayload,
  GitOperationRepoFilesSearchParams,
  GitopsRepositoryReferenceListPayload,
  GitOperationRepoRefsParams,
} from '../portainerEEAPI.schemas';

/**
 * Retrieve the compose file content based on git repository configuration
 **Access policy**: authenticated
 * @summary preview the content of target file in the git repository
 */
export const gitOperationRepoFilePreview = (
  gitopsRepositoryFilePreviewPayload: GitopsRepositoryFilePreviewPayload,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<GitopsFileResponse>> =>
  axios.post(
    `/gitops/repo/file/preview`,
    gitopsRepositoryFilePreviewPayload,
    options
  );

export const getGitOperationRepoFilePreviewMutationOptions = <
  TError = AxiosError<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof gitOperationRepoFilePreview>>,
    TError,
    { data: GitopsRepositoryFilePreviewPayload },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof gitOperationRepoFilePreview>>,
  TError,
  { data: GitopsRepositoryFilePreviewPayload },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof gitOperationRepoFilePreview>>,
    { data: GitopsRepositoryFilePreviewPayload }
  > = (props) => {
    const { data } = props ?? {};

    return gitOperationRepoFilePreview(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GitOperationRepoFilePreviewMutationResult = NonNullable<
  Awaited<ReturnType<typeof gitOperationRepoFilePreview>>
>;
export type GitOperationRepoFilePreviewMutationBody =
  GitopsRepositoryFilePreviewPayload;
export type GitOperationRepoFilePreviewMutationError = AxiosError<void>;

export const useGitOperationRepoFilePreview = <
  TError = AxiosError<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof gitOperationRepoFilePreview>>,
    TError,
    { data: GitopsRepositoryFilePreviewPayload },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions =
    getGitOperationRepoFilePreviewMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Search the file path from the git repository based on partial or completed filename
 **Access policy**: authenticated
 * @summary Search the file path from a git repository files with specified extensions
 */
export const gitOperationRepoFilesSearch = (
  gitopsRepositoryFileSearchPayload: GitopsRepositoryFileSearchPayload,
  params?: GitOperationRepoFilesSearchParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<string[]>> =>
  axios.post(`/gitops/repo/files/search`, gitopsRepositoryFileSearchPayload, {
    ...options,
    params: { ...params, ...options?.params },
  });

export const getGitOperationRepoFilesSearchMutationOptions = <
  TError = AxiosError<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof gitOperationRepoFilesSearch>>,
    TError,
    {
      data: GitopsRepositoryFileSearchPayload;
      params?: GitOperationRepoFilesSearchParams;
    },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof gitOperationRepoFilesSearch>>,
  TError,
  {
    data: GitopsRepositoryFileSearchPayload;
    params?: GitOperationRepoFilesSearchParams;
  },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof gitOperationRepoFilesSearch>>,
    {
      data: GitopsRepositoryFileSearchPayload;
      params?: GitOperationRepoFilesSearchParams;
    }
  > = (props) => {
    const { data, params } = props ?? {};

    return gitOperationRepoFilesSearch(data, params, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GitOperationRepoFilesSearchMutationResult = NonNullable<
  Awaited<ReturnType<typeof gitOperationRepoFilesSearch>>
>;
export type GitOperationRepoFilesSearchMutationBody =
  GitopsRepositoryFileSearchPayload;
export type GitOperationRepoFilesSearchMutationError = AxiosError<void>;

export const useGitOperationRepoFilesSearch = <
  TError = AxiosError<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof gitOperationRepoFilesSearch>>,
    TError,
    {
      data: GitopsRepositoryFileSearchPayload;
      params?: GitOperationRepoFilesSearchParams;
    },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions =
    getGitOperationRepoFilesSearchMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * List all the refs of a git repository
Will return all refs of a git repository
**Access policy**: authenticated
 * @summary List the refs of a git repository
 */
export const gitOperationRepoRefs = (
  gitopsRepositoryReferenceListPayload: GitopsRepositoryReferenceListPayload,
  params?: GitOperationRepoRefsParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<string[]>> =>
  axios.post(`/gitops/repo/refs`, gitopsRepositoryReferenceListPayload, {
    ...options,
    params: { ...params, ...options?.params },
  });

export const getGitOperationRepoRefsMutationOptions = <
  TError = AxiosError<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof gitOperationRepoRefs>>,
    TError,
    {
      data: GitopsRepositoryReferenceListPayload;
      params?: GitOperationRepoRefsParams;
    },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof gitOperationRepoRefs>>,
  TError,
  {
    data: GitopsRepositoryReferenceListPayload;
    params?: GitOperationRepoRefsParams;
  },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof gitOperationRepoRefs>>,
    {
      data: GitopsRepositoryReferenceListPayload;
      params?: GitOperationRepoRefsParams;
    }
  > = (props) => {
    const { data, params } = props ?? {};

    return gitOperationRepoRefs(data, params, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GitOperationRepoRefsMutationResult = NonNullable<
  Awaited<ReturnType<typeof gitOperationRepoRefs>>
>;
export type GitOperationRepoRefsMutationBody =
  GitopsRepositoryReferenceListPayload;
export type GitOperationRepoRefsMutationError = AxiosError<void>;

export const useGitOperationRepoRefs = <
  TError = AxiosError<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof gitOperationRepoRefs>>,
    TError,
    {
      data: GitopsRepositoryReferenceListPayload;
      params?: GitOperationRepoRefsParams;
    },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getGitOperationRepoRefsMutationOptions(options);

  return useMutation(mutationOptions);
};
