/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * PortainerEE API
 * Portainer API is an HTTP API served by Portainer. It is used by the Portainer UI and everything you can do with the UI can be done using the HTTP API.
Examples are available at https://documentation.portainer.io/api/api-examples/
You can find out more about Portainer at [http://portainer.io](http://portainer.io) and get some support on [Slack](http://portainer.io/slack/).

# Authentication

Most of the API environments(endpoints) require to be authenticated as well as some level of authorization to be used.
Portainer API uses JSON Web Token to manage authentication and thus requires you to provide a token in the **Authorization** header of each request
with the **Bearer** authentication mechanism.

Example:

```
Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOjEsImV4cCI6MTQ5OTM3NjE1NH0.NJ6vE8FY1WG6jsRQzfMqeatJ4vh2TWAeeYfDhP71YEE
```

# Security

Each API environment(endpoint) has an associated access policy, it is documented in the description of each environment(endpoint).

Different access policies are available:

- Public access
- Authenticated access
- Restricted access
- Administrator access

### Public access

No authentication is required to access the environments(endpoints) with this access policy.

### Authenticated access

Authentication is required to access the environments(endpoints) with this access policy.

### Restricted access

Authentication is required to access the environments(endpoints) with this access policy.
Extra-checks might be added to ensure access to the resource is granted. Returned data might also be filtered.

### Administrator access

Authentication as well as an administrator role are required to access the environments(endpoints) with this access policy.

# Execute Docker requests

Portainer **DO NOT** expose specific environments(endpoints) to manage your Docker resources (create a container, remove a volume, etc...).

Instead, it acts as a reverse-proxy to the Docker HTTP API. This means that you can execute Docker requests **via** the Portainer HTTP API.

To do so, you can use the `/endpoints/{id}/docker` Portainer API environment(endpoint) (which is not documented below due to Swagger limitations). This environment(endpoint) has a restricted access policy so you still need to be authenticated to be able to query this environment(endpoint). Any query on this environment(endpoint) will be proxied to the Docker API of the associated environment(endpoint) (requests and responses objects are the same as documented in the Docker API).

# Private Registry

Using private registry, you will need to pass a based64 encoded JSON string ‘{"registryId":\<registryID value\>}’ inside the Request Header. The parameter name is "X-Registry-Auth".
\<registryID value\> - The registry ID where the repository was created.

Example:

```
eyJyZWdpc3RyeUlkIjoxfQ==
```

**NOTE**: You can find more information on how to query the Docker API in the [Docker official documentation](https://docs.docker.com/engine/api/v1.30/) as well as in [this Portainer example](https://documentation.portainer.io/api/api-examples/).

 * OpenAPI spec version: 2.19.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse, AxiosError } from 'axios';
import { useQuery, useMutation } from 'react-query';
import type {
  UseQueryOptions,
  UseMutationOptions,
  QueryFunction,
  MutationFunction,
  UseQueryResult,
  QueryKey,
} from 'react-query';

import type {
  ReleaseReleaseElement,
  HelmListParams,
  ReleaseRelease,
  HelmInstallChartPayload,
  HelmDeleteParams,
  HelmHelmUserRepositoryResponse,
  PortainereeHelmUserRepository,
  HelmAddHelmRepoUrlPayload,
  HelmRepoSearchParams,
  HelmShowParams,
} from '../portainerEEAPI.schemas';

/**
 * **Access policy**: authenticated
 * @summary List Helm Releases
 */
export const helmList = (
  id: number,
  params?: HelmListParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<ReleaseReleaseElement[]>> =>
  axios.get(`/endpoints/${id}/kubernetes/helm`, {
    ...options,
    params: { ...params, ...options?.params },
  });

export const getHelmListQueryKey = (id: number, params?: HelmListParams) =>
  [`/endpoints/${id}/kubernetes/helm`, ...(params ? [params] : [])] as const;

export const getHelmListQueryOptions = <
  TData = Awaited<ReturnType<typeof helmList>>,
  TError = AxiosError<void>
>(
  id: number,
  params?: HelmListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof helmList>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryOptions<Awaited<ReturnType<typeof helmList>>, TError, TData> & {
  queryKey: QueryKey;
} => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHelmListQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof helmList>>> = ({
    signal,
  }) => helmList(id, params, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions };
};

export type HelmListQueryResult = NonNullable<
  Awaited<ReturnType<typeof helmList>>
>;
export type HelmListQueryError = AxiosError<void>;

export const useHelmList = <
  TData = Awaited<ReturnType<typeof helmList>>,
  TError = AxiosError<void>
>(
  id: number,
  params?: HelmListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof helmList>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getHelmListQueryOptions(id, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * **Access policy**: authenticated
 * @summary Install Helm Chart
 */
export const helmInstall = (
  id: number,
  helmInstallChartPayload: HelmInstallChartPayload,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<ReleaseRelease>> =>
  axios.post(
    `/endpoints/${id}/kubernetes/helm`,
    helmInstallChartPayload,
    options
  );

export const getHelmInstallMutationOptions = <
  TError = AxiosError<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof helmInstall>>,
    TError,
    { id: number; data: HelmInstallChartPayload },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof helmInstall>>,
  TError,
  { id: number; data: HelmInstallChartPayload },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof helmInstall>>,
    { id: number; data: HelmInstallChartPayload }
  > = (props) => {
    const { id, data } = props ?? {};

    return helmInstall(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type HelmInstallMutationResult = NonNullable<
  Awaited<ReturnType<typeof helmInstall>>
>;
export type HelmInstallMutationBody = HelmInstallChartPayload;
export type HelmInstallMutationError = AxiosError<void>;

export const useHelmInstall = <
  TError = AxiosError<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof helmInstall>>,
    TError,
    { id: number; data: HelmInstallChartPayload },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getHelmInstallMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * **Access policy**: authenticated
 * @summary Delete Helm Release
 */
export const helmDelete = (
  id: number,
  release: string,
  params?: HelmDeleteParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> =>
  axios.delete(`/endpoints/${id}/kubernetes/helm/${release}`, {
    ...options,
    params: { ...params, ...options?.params },
  });

export const getHelmDeleteMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof helmDelete>>,
    TError,
    { id: number; release: string; params?: HelmDeleteParams },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof helmDelete>>,
  TError,
  { id: number; release: string; params?: HelmDeleteParams },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof helmDelete>>,
    { id: number; release: string; params?: HelmDeleteParams }
  > = (props) => {
    const { id, release, params } = props ?? {};

    return helmDelete(id, release, params, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type HelmDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof helmDelete>>
>;

export type HelmDeleteMutationError = AxiosError<unknown>;

export const useHelmDelete = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof helmDelete>>,
    TError,
    { id: number; release: string; params?: HelmDeleteParams },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getHelmDeleteMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Inspect a user helm repositories.
 **Access policy**: authenticated
 * @summary List a users helm repositories
 */
export const helmUserRepositoriesList = (
  id: number,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<HelmHelmUserRepositoryResponse>> =>
  axios.get(`/endpoints/${id}/kubernetes/helm/repositories`, options);

export const getHelmUserRepositoriesListQueryKey = (id: number) =>
  [`/endpoints/${id}/kubernetes/helm/repositories`] as const;

export const getHelmUserRepositoriesListQueryOptions = <
  TData = Awaited<ReturnType<typeof helmUserRepositoriesList>>,
  TError = AxiosError<void>
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof helmUserRepositoriesList>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryOptions<
  Awaited<ReturnType<typeof helmUserRepositoriesList>>,
  TError,
  TData
> & { queryKey: QueryKey } => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getHelmUserRepositoriesListQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof helmUserRepositoriesList>>
  > = ({ signal }) => helmUserRepositoriesList(id, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions };
};

export type HelmUserRepositoriesListQueryResult = NonNullable<
  Awaited<ReturnType<typeof helmUserRepositoriesList>>
>;
export type HelmUserRepositoriesListQueryError = AxiosError<void>;

export const useHelmUserRepositoriesList = <
  TData = Awaited<ReturnType<typeof helmUserRepositoriesList>>,
  TError = AxiosError<void>
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof helmUserRepositoriesList>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getHelmUserRepositoriesListQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Create a user helm repository.
 **Access policy**: authenticated
 * @summary Create a user helm repository
 */
export const helmUserRepositoryCreate = (
  id: number,
  helmAddHelmRepoUrlPayload: HelmAddHelmRepoUrlPayload,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PortainereeHelmUserRepository>> =>
  axios.post(
    `/endpoints/${id}/kubernetes/helm/repositories`,
    helmAddHelmRepoUrlPayload,
    options
  );

export const getHelmUserRepositoryCreateMutationOptions = <
  TError = AxiosError<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof helmUserRepositoryCreate>>,
    TError,
    { id: number; data: HelmAddHelmRepoUrlPayload },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof helmUserRepositoryCreate>>,
  TError,
  { id: number; data: HelmAddHelmRepoUrlPayload },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof helmUserRepositoryCreate>>,
    { id: number; data: HelmAddHelmRepoUrlPayload }
  > = (props) => {
    const { id, data } = props ?? {};

    return helmUserRepositoryCreate(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type HelmUserRepositoryCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof helmUserRepositoryCreate>>
>;
export type HelmUserRepositoryCreateMutationBody = HelmAddHelmRepoUrlPayload;
export type HelmUserRepositoryCreateMutationError = AxiosError<void>;

export const useHelmUserRepositoryCreate = <
  TError = AxiosError<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof helmUserRepositoryCreate>>,
    TError,
    { id: number; data: HelmAddHelmRepoUrlPayload },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getHelmUserRepositoryCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * **Access policy**: authenticated
 * @summary Search Helm Charts
 */
export const helmRepoSearch = (
  params: HelmRepoSearchParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<string>> =>
  axios.get(`/templates/helm`, {
    ...options,
    params: { ...params, ...options?.params },
  });

export const getHelmRepoSearchQueryKey = (params: HelmRepoSearchParams) =>
  [`/templates/helm`, ...(params ? [params] : [])] as const;

export const getHelmRepoSearchQueryOptions = <
  TData = Awaited<ReturnType<typeof helmRepoSearch>>,
  TError = AxiosError<void>
>(
  params: HelmRepoSearchParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof helmRepoSearch>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryOptions<
  Awaited<ReturnType<typeof helmRepoSearch>>,
  TError,
  TData
> & { queryKey: QueryKey } => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHelmRepoSearchQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof helmRepoSearch>>> = ({
    signal,
  }) => helmRepoSearch(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions };
};

export type HelmRepoSearchQueryResult = NonNullable<
  Awaited<ReturnType<typeof helmRepoSearch>>
>;
export type HelmRepoSearchQueryError = AxiosError<void>;

export const useHelmRepoSearch = <
  TData = Awaited<ReturnType<typeof helmRepoSearch>>,
  TError = AxiosError<void>
>(
  params: HelmRepoSearchParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof helmRepoSearch>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getHelmRepoSearchQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * **Access policy**: authenticated
 * @summary Show Helm Chart Information
 */
export const helmShow = (
  command: string,
  params: HelmShowParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<string>> =>
  axios.get(`/templates/helm/${command}`, {
    ...options,
    params: { ...params, ...options?.params },
  });

export const getHelmShowQueryKey = (command: string, params: HelmShowParams) =>
  [`/templates/helm/${command}`, ...(params ? [params] : [])] as const;

export const getHelmShowQueryOptions = <
  TData = Awaited<ReturnType<typeof helmShow>>,
  TError = AxiosError<void>
>(
  command: string,
  params: HelmShowParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof helmShow>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryOptions<Awaited<ReturnType<typeof helmShow>>, TError, TData> & {
  queryKey: QueryKey;
} => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getHelmShowQueryKey(command, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof helmShow>>> = ({
    signal,
  }) => helmShow(command, params, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!command, ...queryOptions };
};

export type HelmShowQueryResult = NonNullable<
  Awaited<ReturnType<typeof helmShow>>
>;
export type HelmShowQueryError = AxiosError<void>;

export const useHelmShow = <
  TData = Awaited<ReturnType<typeof helmShow>>,
  TError = AxiosError<void>
>(
  command: string,
  params: HelmShowParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof helmShow>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getHelmShowQueryOptions(command, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
