// Code generated by "stringer -type=ProvisioningState -trimprefix=ps"; DO NOT EDIT.

package cloud

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProvisioningStatePending-0]
	_ = x[ProvisioningStateWaitingForCluster-1]
	_ = x[ProvisioningStateAgentSetup-2]
	_ = x[ProvisioningStateWaitingForAgent-3]
	_ = x[ProvisioningStateUpdatingEndpoint-4]
	_ = x[ProvisioningStateDone-5]
}

const _ProvisioningState_name = "PendingWaitingForClusterAgentSetupWaitingForAgentUpdatingEndpointDone"

var _ProvisioningState_index = [...]uint8{0, 7, 24, 34, 49, 65, 69}

func (i ProvisioningState) String() string {
	if i < 0 || i >= ProvisioningState(len(_ProvisioningState_index)-1) {
		return "ProvisioningState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProvisioningState_name[_ProvisioningState_index[i]:_ProvisioningState_index[i+1]]
}
