// Code generated by "stringer -type=ProvisioningState -trimprefix=ProvisioningState"; DO NOT EDIT.

package cloud

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProvisioningStatePending-0]
	_ = x[ProvisioningStateWaitingForCluster-1]
	_ = x[ProvisioningStateDeployingCustomTemplate-2]
	_ = x[ProvisioningStateAgentSetup-3]
	_ = x[ProvisioningStateWaitingForAgent-4]
	_ = x[ProvisioningStateUpdatingEnvironment-5]
	_ = x[ProvisioningStateDone-6]
}

const _ProvisioningState_name = "PendingWaitingForClusterDeployingCustomTemplateAgentSetupWaitingForAgentUpdatingEnvironmentDone"

var _ProvisioningState_index = [...]uint8{0, 7, 24, 47, 57, 72, 91, 95}

func (i ProvisioningState) String() string {
	if i < 0 || i >= ProvisioningState(len(_ProvisioningState_index)-1) {
		return "ProvisioningState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProvisioningState_name[_ProvisioningState_index[i]:_ProvisioningState_index[i+1]]
}
