/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * PortainerEE API
 * Portainer API is an HTTP API served by Portainer. It is used by the Portainer UI and everything you can do with the UI can be done using the HTTP API.
Examples are available at https://documentation.portainer.io/api/api-examples/
You can find out more about Portainer at [http://portainer.io](http://portainer.io) and get some support on [Slack](http://portainer.io/slack/).

# Authentication

Most of the API environments(endpoints) require to be authenticated as well as some level of authorization to be used.
Portainer API uses JSON Web Token to manage authentication and thus requires you to provide a token in the **Authorization** header of each request
with the **Bearer** authentication mechanism.

Example:

```
Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOjEsImV4cCI6MTQ5OTM3NjE1NH0.NJ6vE8FY1WG6jsRQzfMqeatJ4vh2TWAeeYfDhP71YEE
```

# Security

Each API environment(endpoint) has an associated access policy, it is documented in the description of each environment(endpoint).

Different access policies are available:

- Public access
- Authenticated access
- Restricted access
- Administrator access

### Public access

No authentication is required to access the environments(endpoints) with this access policy.

### Authenticated access

Authentication is required to access the environments(endpoints) with this access policy.

### Restricted access

Authentication is required to access the environments(endpoints) with this access policy.
Extra-checks might be added to ensure access to the resource is granted. Returned data might also be filtered.

### Administrator access

Authentication as well as an administrator role are required to access the environments(endpoints) with this access policy.

# Execute Docker requests

Portainer **DO NOT** expose specific environments(endpoints) to manage your Docker resources (create a container, remove a volume, etc...).

Instead, it acts as a reverse-proxy to the Docker HTTP API. This means that you can execute Docker requests **via** the Portainer HTTP API.

To do so, you can use the `/endpoints/{id}/docker` Portainer API environment(endpoint) (which is not documented below due to Swagger limitations). This environment(endpoint) has a restricted access policy so you still need to be authenticated to be able to query this environment(endpoint). Any query on this environment(endpoint) will be proxied to the Docker API of the associated environment(endpoint) (requests and responses objects are the same as documented in the Docker API).

# Private Registry

Using private registry, you will need to pass a based64 encoded JSON string ‘{"registryId":\<registryID value\>}’ inside the Request Header. The parameter name is "X-Registry-Auth".
\<registryID value\> - The registry ID where the repository was created.

Example:

```
eyJyZWdpc3RyeUlkIjoxfQ==
```

**NOTE**: You can find more information on how to query the Docker API in the [Docker official documentation](https://docs.docker.com/engine/api/v1.30/) as well as in [this Portainer example](https://documentation.portainer.io/api/api-examples/).

 * OpenAPI spec version: 2.19.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse, AxiosError } from 'axios';
import { useMutation } from 'react-query';
import type { UseMutationOptions, MutationFunction } from 'react-query';

import type {
  LdapAdminGroupsPayload,
  LdapCheckPayload,
  PortainereeLDAPUser,
  LdapGroupsPayload,
  LdapTestLoginResponse,
  LdapTestLoginPayload,
  LdapUsersPayload,
} from '../portainerEEAPI.schemas';

/**
 * Fetch LDAP admin groups from LDAP server based on AdminGroupSearchSettings
 **Access policy**: administrator
 * @summary Fetch LDAP admin groups
 */
export const lDAPAdminGroups = (
  ldapAdminGroupsPayload: LdapAdminGroupsPayload,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<string[]>> =>
  axios.post(`/ldap/admin-groups`, ldapAdminGroupsPayload, options);

export const getLDAPAdminGroupsMutationOptions = <
  TError = AxiosError<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof lDAPAdminGroups>>,
    TError,
    { data: LdapAdminGroupsPayload },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof lDAPAdminGroups>>,
  TError,
  { data: LdapAdminGroupsPayload },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof lDAPAdminGroups>>,
    { data: LdapAdminGroupsPayload }
  > = (props) => {
    const { data } = props ?? {};

    return lDAPAdminGroups(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LDAPAdminGroupsMutationResult = NonNullable<
  Awaited<ReturnType<typeof lDAPAdminGroups>>
>;
export type LDAPAdminGroupsMutationBody = LdapAdminGroupsPayload;
export type LDAPAdminGroupsMutationError = AxiosError<void>;

export const useLDAPAdminGroups = <
  TError = AxiosError<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof lDAPAdminGroups>>,
    TError,
    { data: LdapAdminGroupsPayload },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getLDAPAdminGroupsMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Test LDAP connectivity using LDAP details
 **Access policy**: administrator
 * @summary Test LDAP connectivity
 */
export const lDAPCheck = (
  ldapCheckPayload: LdapCheckPayload,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> =>
  axios.post(`/ldap/check`, ldapCheckPayload, options);

export const getLDAPCheckMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof lDAPCheck>>,
    TError,
    { data: LdapCheckPayload },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof lDAPCheck>>,
  TError,
  { data: LdapCheckPayload },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof lDAPCheck>>,
    { data: LdapCheckPayload }
  > = (props) => {
    const { data } = props ?? {};

    return lDAPCheck(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LDAPCheckMutationResult = NonNullable<
  Awaited<ReturnType<typeof lDAPCheck>>
>;
export type LDAPCheckMutationBody = LdapCheckPayload;
export type LDAPCheckMutationError = AxiosError<unknown>;

export const useLDAPCheck = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof lDAPCheck>>,
    TError,
    { data: LdapCheckPayload },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getLDAPCheckMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * **Access policy**: administrator
 * @summary Search LDAP Groups
 */
export const lDAPGroups = (
  ldapGroupsPayload: LdapGroupsPayload,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PortainereeLDAPUser[]>> =>
  axios.post(`/ldap/groups`, ldapGroupsPayload, options);

export const getLDAPGroupsMutationOptions = <
  TError = AxiosError<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof lDAPGroups>>,
    TError,
    { data: LdapGroupsPayload },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof lDAPGroups>>,
  TError,
  { data: LdapGroupsPayload },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof lDAPGroups>>,
    { data: LdapGroupsPayload }
  > = (props) => {
    const { data } = props ?? {};

    return lDAPGroups(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LDAPGroupsMutationResult = NonNullable<
  Awaited<ReturnType<typeof lDAPGroups>>
>;
export type LDAPGroupsMutationBody = LdapGroupsPayload;
export type LDAPGroupsMutationError = AxiosError<void>;

export const useLDAPGroups = <
  TError = AxiosError<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof lDAPGroups>>,
    TError,
    { data: LdapGroupsPayload },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getLDAPGroupsMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * **Access policy**: administrator
 * @summary Test Login to ldap server
 */
export const lDAPTestLogin = (
  ldapTestLoginPayload: LdapTestLoginPayload,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<LdapTestLoginResponse>> =>
  axios.post(`/ldap/test`, ldapTestLoginPayload, options);

export const getLDAPTestLoginMutationOptions = <
  TError = AxiosError<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof lDAPTestLogin>>,
    TError,
    { data: LdapTestLoginPayload },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof lDAPTestLogin>>,
  TError,
  { data: LdapTestLoginPayload },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof lDAPTestLogin>>,
    { data: LdapTestLoginPayload }
  > = (props) => {
    const { data } = props ?? {};

    return lDAPTestLogin(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LDAPTestLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof lDAPTestLogin>>
>;
export type LDAPTestLoginMutationBody = LdapTestLoginPayload;
export type LDAPTestLoginMutationError = AxiosError<void>;

export const useLDAPTestLogin = <
  TError = AxiosError<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof lDAPTestLogin>>,
    TError,
    { data: LdapTestLoginPayload },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getLDAPTestLoginMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * **Access policy**: administrator
 * @summary Search LDAP Users
 */
export const lDAPUsers = (
  ldapUsersPayload: LdapUsersPayload,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PortainereeLDAPUser[]>> =>
  axios.post(`/ldap/users`, ldapUsersPayload, options);

export const getLDAPUsersMutationOptions = <
  TError = AxiosError<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof lDAPUsers>>,
    TError,
    { data: LdapUsersPayload },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof lDAPUsers>>,
  TError,
  { data: LdapUsersPayload },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof lDAPUsers>>,
    { data: LdapUsersPayload }
  > = (props) => {
    const { data } = props ?? {};

    return lDAPUsers(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LDAPUsersMutationResult = NonNullable<
  Awaited<ReturnType<typeof lDAPUsers>>
>;
export type LDAPUsersMutationBody = LdapUsersPayload;
export type LDAPUsersMutationError = AxiosError<void>;

export const useLDAPUsers = <
  TError = AxiosError<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof lDAPUsers>>,
    TError,
    { data: LdapUsersPayload },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getLDAPUsersMutationOptions(options);

  return useMutation(mutationOptions);
};
