/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * PortainerEE API
 * Portainer API is an HTTP API served by Portainer. It is used by the Portainer UI and everything you can do with the UI can be done using the HTTP API.
Examples are available at https://documentation.portainer.io/api/api-examples/
You can find out more about Portainer at [http://portainer.io](http://portainer.io) and get some support on [Slack](http://portainer.io/slack/).

# Authentication

Most of the API environments(endpoints) require to be authenticated as well as some level of authorization to be used.
Portainer API uses JSON Web Token to manage authentication and thus requires you to provide a token in the **Authorization** header of each request
with the **Bearer** authentication mechanism.

Example:

```
Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOjEsImV4cCI6MTQ5OTM3NjE1NH0.NJ6vE8FY1WG6jsRQzfMqeatJ4vh2TWAeeYfDhP71YEE
```

# Security

Each API environment(endpoint) has an associated access policy, it is documented in the description of each environment(endpoint).

Different access policies are available:

- Public access
- Authenticated access
- Restricted access
- Administrator access

### Public access

No authentication is required to access the environments(endpoints) with this access policy.

### Authenticated access

Authentication is required to access the environments(endpoints) with this access policy.

### Restricted access

Authentication is required to access the environments(endpoints) with this access policy.
Extra-checks might be added to ensure access to the resource is granted. Returned data might also be filtered.

### Administrator access

Authentication as well as an administrator role are required to access the environments(endpoints) with this access policy.

# Execute Docker requests

Portainer **DO NOT** expose specific environments(endpoints) to manage your Docker resources (create a container, remove a volume, etc...).

Instead, it acts as a reverse-proxy to the Docker HTTP API. This means that you can execute Docker requests **via** the Portainer HTTP API.

To do so, you can use the `/endpoints/{id}/docker` Portainer API environment(endpoint) (which is not documented below due to Swagger limitations). This environment(endpoint) has a restricted access policy so you still need to be authenticated to be able to query this environment(endpoint). Any query on this environment(endpoint) will be proxied to the Docker API of the associated environment(endpoint) (requests and responses objects are the same as documented in the Docker API).

# Private Registry

Using private registry, you will need to pass a based64 encoded JSON string ‘{"registryId":\<registryID value\>}’ inside the Request Header. The parameter name is "X-Registry-Auth".
\<registryID value\> - The registry ID where the repository was created.

Example:

```
eyJyZWdpc3RyeUlkIjoxfQ==
```

**NOTE**: You can find more information on how to query the Docker API in the [Docker official documentation](https://docs.docker.com/engine/api/v1.30/) as well as in [this Portainer example](https://documentation.portainer.io/api/api-examples/).

 * OpenAPI spec version: 2.19.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse, AxiosError } from 'axios';
import { useQuery } from 'react-query';
import type {
  UseQueryOptions,
  QueryFunction,
  UseQueryResult,
  QueryKey,
} from 'react-query';

import type {
  GithubComPortainerPortainerEeApiHttpHandlerSystemNodesCountResponse,
  GithubComPortainerPortainerEeApiHttpHandlerSystemStatus,
  GithubComPortainerPortainerEeApiHttpHandlerSystemVersionResponse,
} from '../portainerEEAPI.schemas';

/**
 * **Access policy**: authenticated
 * @summary Retrieve the count of nodes
 */
export const systemNodesCount = (
  options?: AxiosRequestConfig
): Promise<
  AxiosResponse<GithubComPortainerPortainerEeApiHttpHandlerSystemNodesCountResponse>
> => axios.get(`/system/nodes`, options);

export const getSystemNodesCountQueryKey = () => [`/system/nodes`] as const;

export const getSystemNodesCountQueryOptions = <
  TData = Awaited<ReturnType<typeof systemNodesCount>>,
  TError = AxiosError<void>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof systemNodesCount>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}): UseQueryOptions<
  Awaited<ReturnType<typeof systemNodesCount>>,
  TError,
  TData
> & { queryKey: QueryKey } => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSystemNodesCountQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof systemNodesCount>>
  > = ({ signal }) => systemNodesCount({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions };
};

export type SystemNodesCountQueryResult = NonNullable<
  Awaited<ReturnType<typeof systemNodesCount>>
>;
export type SystemNodesCountQueryError = AxiosError<void>;

export const useSystemNodesCount = <
  TData = Awaited<ReturnType<typeof systemNodesCount>>,
  TError = AxiosError<void>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof systemNodesCount>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getSystemNodesCountQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Retrieve Portainer status
 **Access policy**: public
 * @summary Check Portainer status
 */
export const systemStatus = (
  options?: AxiosRequestConfig
): Promise<
  AxiosResponse<GithubComPortainerPortainerEeApiHttpHandlerSystemStatus>
> => axios.get(`/system/status`, options);

export const getSystemStatusQueryKey = () => [`/system/status`] as const;

export const getSystemStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof systemStatus>>,
  TError = AxiosError<unknown>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof systemStatus>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}): UseQueryOptions<Awaited<ReturnType<typeof systemStatus>>, TError, TData> & {
  queryKey: QueryKey;
} => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSystemStatusQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof systemStatus>>> = ({
    signal,
  }) => systemStatus({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions };
};

export type SystemStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof systemStatus>>
>;
export type SystemStatusQueryError = AxiosError<unknown>;

export const useSystemStatus = <
  TData = Awaited<ReturnType<typeof systemStatus>>,
  TError = AxiosError<unknown>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof systemStatus>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getSystemStatusQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Check if portainer has an update available
 **Access policy**: authenticated
 * @summary Check for portainer updates
 */
export const systemVersion = (
  options?: AxiosRequestConfig
): Promise<
  AxiosResponse<GithubComPortainerPortainerEeApiHttpHandlerSystemVersionResponse>
> => axios.get(`/system/version`, options);

export const getSystemVersionQueryKey = () => [`/system/version`] as const;

export const getSystemVersionQueryOptions = <
  TData = Awaited<ReturnType<typeof systemVersion>>,
  TError = AxiosError<unknown>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof systemVersion>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}): UseQueryOptions<
  Awaited<ReturnType<typeof systemVersion>>,
  TError,
  TData
> & { queryKey: QueryKey } => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSystemVersionQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof systemVersion>>> = ({
    signal,
  }) => systemVersion({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions };
};

export type SystemVersionQueryResult = NonNullable<
  Awaited<ReturnType<typeof systemVersion>>
>;
export type SystemVersionQueryError = AxiosError<unknown>;

export const useSystemVersion = <
  TData = Awaited<ReturnType<typeof systemVersion>>,
  TError = AxiosError<unknown>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof systemVersion>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getSystemVersionQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
