/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * PortainerEE API
 * Portainer API is an HTTP API served by Portainer. It is used by the Portainer UI and everything you can do with the UI can be done using the HTTP API.
Examples are available at https://documentation.portainer.io/api/api-examples/
You can find out more about Portainer at [http://portainer.io](http://portainer.io) and get some support on [Slack](http://portainer.io/slack/).

# Authentication

Most of the API environments(endpoints) require to be authenticated as well as some level of authorization to be used.
Portainer API uses JSON Web Token to manage authentication and thus requires you to provide a token in the **Authorization** header of each request
with the **Bearer** authentication mechanism.

Example:

```
Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOjEsImV4cCI6MTQ5OTM3NjE1NH0.NJ6vE8FY1WG6jsRQzfMqeatJ4vh2TWAeeYfDhP71YEE
```

# Security

Each API environment(endpoint) has an associated access policy, it is documented in the description of each environment(endpoint).

Different access policies are available:

- Public access
- Authenticated access
- Restricted access
- Administrator access

### Public access

No authentication is required to access the environments(endpoints) with this access policy.

### Authenticated access

Authentication is required to access the environments(endpoints) with this access policy.

### Restricted access

Authentication is required to access the environments(endpoints) with this access policy.
Extra-checks might be added to ensure access to the resource is granted. Returned data might also be filtered.

### Administrator access

Authentication as well as an administrator role are required to access the environments(endpoints) with this access policy.

# Execute Docker requests

Portainer **DO NOT** expose specific environments(endpoints) to manage your Docker resources (create a container, remove a volume, etc...).

Instead, it acts as a reverse-proxy to the Docker HTTP API. This means that you can execute Docker requests **via** the Portainer HTTP API.

To do so, you can use the `/endpoints/{id}/docker` Portainer API environment(endpoint) (which is not documented below due to Swagger limitations). This environment(endpoint) has a restricted access policy so you still need to be authenticated to be able to query this environment(endpoint). Any query on this environment(endpoint) will be proxied to the Docker API of the associated environment(endpoint) (requests and responses objects are the same as documented in the Docker API).

# Private Registry

Using private registry, you will need to pass a based64 encoded JSON string ‘{"registryId":\<registryID value\>}’ inside the Request Header. The parameter name is "X-Registry-Auth".
\<registryID value\> - The registry ID where the repository was created.

Example:

```
eyJyZWdpc3RyeUlkIjoxfQ==
```

**NOTE**: You can find more information on how to query the Docker API in the [Docker official documentation](https://docs.docker.com/engine/api/v1.30/) as well as in [this Portainer example](https://documentation.portainer.io/api/api-examples/).

 * OpenAPI spec version: 2.19.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse, AxiosError } from 'axios';
import { useQuery } from 'react-query';
import type {
  UseQueryOptions,
  QueryFunction,
  UseQueryResult,
  QueryKey,
} from 'react-query';

import type {
  PortainereeAuthActivityLog,
  AuthLogsListParams,
  AuthLogsCSVParams,
  UseractivityLogsListResponse,
  LogsListParams,
  LogsCSVParams,
} from '../portainerEEAPI.schemas';

/**
 * List logs by provided query
 **Access policy**: admin
 * @summary List auth activity logs
 */
export const authLogsList = (
  params?: AuthLogsListParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PortainereeAuthActivityLog[]>> =>
  axios.get(`/useractivity/authlogs`, {
    ...options,
    params: { ...params, ...options?.params },
  });

export const getAuthLogsListQueryKey = (params?: AuthLogsListParams) =>
  [`/useractivity/authlogs`, ...(params ? [params] : [])] as const;

export const getAuthLogsListQueryOptions = <
  TData = Awaited<ReturnType<typeof authLogsList>>,
  TError = AxiosError<void>
>(
  params?: AuthLogsListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof authLogsList>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryOptions<Awaited<ReturnType<typeof authLogsList>>, TError, TData> & {
  queryKey: QueryKey;
} => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthLogsListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authLogsList>>> = ({
    signal,
  }) => authLogsList(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions };
};

export type AuthLogsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof authLogsList>>
>;
export type AuthLogsListQueryError = AxiosError<void>;

export const useAuthLogsList = <
  TData = Awaited<ReturnType<typeof authLogsList>>,
  TError = AxiosError<void>
>(
  params?: AuthLogsListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof authLogsList>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAuthLogsListQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Download auth logs as CSV by provided query
 **Access policy**: admin
 * @summary Download auth logs as CSV
 */
export const authLogsCSV = (
  params?: AuthLogsCSVParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> =>
  axios.get(`/useractivity/authlogs.csv`, {
    ...options,
    params: { ...params, ...options?.params },
  });

export const getAuthLogsCSVQueryKey = (params?: AuthLogsCSVParams) =>
  [`/useractivity/authlogs.csv`, ...(params ? [params] : [])] as const;

export const getAuthLogsCSVQueryOptions = <
  TData = Awaited<ReturnType<typeof authLogsCSV>>,
  TError = AxiosError<unknown>
>(
  params?: AuthLogsCSVParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof authLogsCSV>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryOptions<Awaited<ReturnType<typeof authLogsCSV>>, TError, TData> & {
  queryKey: QueryKey;
} => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthLogsCSVQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authLogsCSV>>> = ({
    signal,
  }) => authLogsCSV(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions };
};

export type AuthLogsCSVQueryResult = NonNullable<
  Awaited<ReturnType<typeof authLogsCSV>>
>;
export type AuthLogsCSVQueryError = AxiosError<unknown>;

export const useAuthLogsCSV = <
  TData = Awaited<ReturnType<typeof authLogsCSV>>,
  TError = AxiosError<unknown>
>(
  params?: AuthLogsCSVParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof authLogsCSV>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAuthLogsCSVQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * List logs by provided query
 **Access policy**: admin
 * @summary List user activity logs
 */
export const logsList = (
  params?: LogsListParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<UseractivityLogsListResponse>> =>
  axios.get(`/useractivity/logs`, {
    ...options,
    params: { ...params, ...options?.params },
  });

export const getLogsListQueryKey = (params?: LogsListParams) =>
  [`/useractivity/logs`, ...(params ? [params] : [])] as const;

export const getLogsListQueryOptions = <
  TData = Awaited<ReturnType<typeof logsList>>,
  TError = AxiosError<void>
>(
  params?: LogsListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof logsList>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryOptions<Awaited<ReturnType<typeof logsList>>, TError, TData> & {
  queryKey: QueryKey;
} => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getLogsListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof logsList>>> = ({
    signal,
  }) => logsList(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions };
};

export type LogsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof logsList>>
>;
export type LogsListQueryError = AxiosError<void>;

export const useLogsList = <
  TData = Awaited<ReturnType<typeof logsList>>,
  TError = AxiosError<void>
>(
  params?: LogsListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof logsList>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getLogsListQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Download user activity logs as CSV by provided query
 **Access policy**: admin
 * @summary Download user activity logs as CSV
 */
export const logsCSV = (
  params?: LogsCSVParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> =>
  axios.get(`/useractivity/logs.csv`, {
    ...options,
    params: { ...params, ...options?.params },
  });

export const getLogsCSVQueryKey = (params?: LogsCSVParams) =>
  [`/useractivity/logs.csv`, ...(params ? [params] : [])] as const;

export const getLogsCSVQueryOptions = <
  TData = Awaited<ReturnType<typeof logsCSV>>,
  TError = AxiosError<unknown>
>(
  params?: LogsCSVParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof logsCSV>>, TError, TData>;
    axios?: AxiosRequestConfig;
  }
): UseQueryOptions<Awaited<ReturnType<typeof logsCSV>>, TError, TData> & {
  queryKey: QueryKey;
} => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getLogsCSVQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof logsCSV>>> = ({
    signal,
  }) => logsCSV(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions };
};

export type LogsCSVQueryResult = NonNullable<
  Awaited<ReturnType<typeof logsCSV>>
>;
export type LogsCSVQueryError = AxiosError<unknown>;

export const useLogsCSV = <
  TData = Awaited<ReturnType<typeof logsCSV>>,
  TError = AxiosError<unknown>
>(
  params?: LogsCSVParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof logsCSV>>, TError, TData>;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getLogsCSVQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
