name: Test
on: push
jobs:
  test-client:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn --frozen-lockfile

      - name: Run tests
        run: yarn test:client
  # test-server:
  #   runs-on: ubuntu-latest
  #   env:
  #     GOPRIVATE: "github.com/portainer"
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: webfactory/ssh-agent@v0.5.4
  #       with:
  #         ssh-private-key: ${{ secrets.DEPLOY_KEY_LIBLICENSE }}
  #     - uses: actions/setup-go@v3
  #       with:
  #         go-version: '1.18'
  #     - name: Configure git for private modules
  #       run: git config --global url."git@github.com:".insteadOf "https://github.com"
  #     - name: Run tests
  #       run: |
  #         cd api 
  #         go test ./...

