/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Docker Engine API
 * The Engine API is an HTTP API served by Docker Engine. It is the API the
Docker client uses to communicate with the Engine, so everything the Docker
client can do can be done with the API.

Most of the client's commands map directly to API endpoints (e.g. `docker ps`
is `GET /containers/json`). The notable exception is running containers,
which consists of several API calls.

# Errors

The API uses standard HTTP status codes to indicate the success or failure
of the API call. The body of the response will be JSON in the following
format:

```
{
  "message": "page not found"
}
```

# Versioning

The API is usually changed in each release, so API calls are versioned to
ensure that clients don't break. To lock to a specific version of the API,
you prefix the URL with its version, for example, call `/v1.30/info` to use
the v1.30 version of the `/info` endpoint. If the API version specified in
the URL is not supported by the daemon, a HTTP `400 Bad Request` error message
is returned.

If you omit the version-prefix, the current version of the API (v1.41) is used.
For example, calling `/info` is the same as calling `/v1.41/info`. Using the
API without a version-prefix is deprecated and will be removed in a future release.

Engine releases in the near future should support this version of the API,
so your client will continue to work even if it is talking to a newer Engine.

The API uses an open schema model, which means server may add extra properties
to responses. Likewise, the server will ignore any extra query parameters and
request body properties. When you write clients, you need to ignore additional
properties in responses to ensure they do not break when talking to newer
daemons.


# Authentication

Authentication for registries is handled client side. The client has to send
authentication details to various endpoints that need to communicate with
registries, such as `POST /images/(name)/push`. These are sent as
`X-Registry-Auth` header as a [base64url encoded](https://tools.ietf.org/html/rfc4648#section-5)
(JSON) string with the following structure:

```
{
  "username": "string",
  "password": "string",
  "email": "string",
  "serveraddress": "string"
}
```

The `serveraddress` is a domain/IP without a protocol. Throughout this
structure, double quotes are required.

If you have already got an identity token from the [`/auth` endpoint](#operation/SystemAuth),
you can just pass this instead of credentials:

```
{
  "identitytoken": "9cbaf023786cd7..."
}
```

 * OpenAPI spec version: 1.41
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse, AxiosError } from 'axios';
import { useQuery, useMutation } from 'react-query';
import type {
  UseQueryOptions,
  UseMutationOptions,
  QueryFunction,
  MutationFunction,
  UseQueryResult,
  QueryKey,
} from 'react-query';

import type {
  Secret,
  ErrorResponse,
  SecretListParams,
  IdResponse,
  SecretCreateBody,
  SecretSpec,
  SecretUpdateParams,
} from '../dockerEngineAPI.schemas';

/**
 * @summary List secrets
 */
export const secretList = (
  endpointId: number,
  params?: SecretListParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<Secret[]>> =>
  axios.get(`/endpoints/${endpointId}/docker/secrets`, {
    ...options,
    params: { ...params, ...options?.params },
  });

export const getSecretListQueryKey = (
  endpointId: number,
  params?: SecretListParams
) =>
  [
    `/endpoints/${endpointId}/docker/secrets`,
    ...(params ? [params] : []),
  ] as const;

export const getSecretListQueryOptions = <
  TData = Awaited<ReturnType<typeof secretList>>,
  TError = AxiosError<ErrorResponse>
>(
  endpointId: number,
  params?: SecretListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof secretList>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryOptions<Awaited<ReturnType<typeof secretList>>, TError, TData> & {
  queryKey: QueryKey;
} => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSecretListQueryKey(endpointId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof secretList>>> = ({
    signal,
  }) => secretList(endpointId, params, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!endpointId, ...queryOptions };
};

export type SecretListQueryResult = NonNullable<
  Awaited<ReturnType<typeof secretList>>
>;
export type SecretListQueryError = AxiosError<ErrorResponse>;

export const useSecretList = <
  TData = Awaited<ReturnType<typeof secretList>>,
  TError = AxiosError<ErrorResponse>
>(
  endpointId: number,
  params?: SecretListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof secretList>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getSecretListQueryOptions(endpointId, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Create a secret
 */
export const secretCreate = (
  endpointId: number,
  secretCreateBody: SecretCreateBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<IdResponse>> =>
  axios.post(
    `/endpoints/${endpointId}/docker/secrets/create`,
    secretCreateBody,
    options
  );

export const getSecretCreateMutationOptions = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof secretCreate>>,
    TError,
    { endpointId: number; data: SecretCreateBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof secretCreate>>,
  TError,
  { endpointId: number; data: SecretCreateBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof secretCreate>>,
    { endpointId: number; data: SecretCreateBody }
  > = (props) => {
    const { endpointId, data } = props ?? {};

    return secretCreate(endpointId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SecretCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof secretCreate>>
>;
export type SecretCreateMutationBody = SecretCreateBody;
export type SecretCreateMutationError = AxiosError<ErrorResponse>;

export const useSecretCreate = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof secretCreate>>,
    TError,
    { endpointId: number; data: SecretCreateBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getSecretCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Inspect a secret
 */
export const secretInspect = (
  endpointId: number,
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<Secret>> =>
  axios.get(`/endpoints/${endpointId}/docker/secrets/${id}`, options);

export const getSecretInspectQueryKey = (endpointId: number, id: string) =>
  [`/endpoints/${endpointId}/docker/secrets/${id}`] as const;

export const getSecretInspectQueryOptions = <
  TData = Awaited<ReturnType<typeof secretInspect>>,
  TError = AxiosError<ErrorResponse>
>(
  endpointId: number,
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof secretInspect>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryOptions<Awaited<ReturnType<typeof secretInspect>>, TError, TData> & {
  queryKey: QueryKey;
} => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSecretInspectQueryKey(endpointId, id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof secretInspect>>> = ({
    signal,
  }) => secretInspect(endpointId, id, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!(endpointId && id), ...queryOptions };
};

export type SecretInspectQueryResult = NonNullable<
  Awaited<ReturnType<typeof secretInspect>>
>;
export type SecretInspectQueryError = AxiosError<ErrorResponse>;

export const useSecretInspect = <
  TData = Awaited<ReturnType<typeof secretInspect>>,
  TError = AxiosError<ErrorResponse>
>(
  endpointId: number,
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof secretInspect>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getSecretInspectQueryOptions(endpointId, id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Delete a secret
 */
export const secretDelete = (
  endpointId: number,
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> =>
  axios.delete(`/endpoints/${endpointId}/docker/secrets/${id}`, options);

export const getSecretDeleteMutationOptions = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof secretDelete>>,
    TError,
    { endpointId: number; id: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof secretDelete>>,
  TError,
  { endpointId: number; id: string },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof secretDelete>>,
    { endpointId: number; id: string }
  > = (props) => {
    const { endpointId, id } = props ?? {};

    return secretDelete(endpointId, id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SecretDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof secretDelete>>
>;

export type SecretDeleteMutationError = AxiosError<ErrorResponse>;

export const useSecretDelete = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof secretDelete>>,
    TError,
    { endpointId: number; id: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getSecretDeleteMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Update a Secret
 */
export const secretUpdate = (
  endpointId: number,
  id: string,
  secretSpec: SecretSpec,
  params: SecretUpdateParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> =>
  axios.post(
    `/endpoints/${endpointId}/docker/secrets/${id}/update`,
    secretSpec,
    {
      ...options,
      params: { ...params, ...options?.params },
    }
  );

export const getSecretUpdateMutationOptions = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof secretUpdate>>,
    TError,
    {
      endpointId: number;
      id: string;
      data: SecretSpec;
      params: SecretUpdateParams;
    },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof secretUpdate>>,
  TError,
  {
    endpointId: number;
    id: string;
    data: SecretSpec;
    params: SecretUpdateParams;
  },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof secretUpdate>>,
    {
      endpointId: number;
      id: string;
      data: SecretSpec;
      params: SecretUpdateParams;
    }
  > = (props) => {
    const { endpointId, id, data, params } = props ?? {};

    return secretUpdate(endpointId, id, data, params, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SecretUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof secretUpdate>>
>;
export type SecretUpdateMutationBody = SecretSpec;
export type SecretUpdateMutationError = AxiosError<ErrorResponse>;

export const useSecretUpdate = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof secretUpdate>>,
    TError,
    {
      endpointId: number;
      id: string;
      data: SecretSpec;
      params: SecretUpdateParams;
    },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getSecretUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};
